name: Generate Marp Slides
on:
  push:
    paths:
      - 'slides.md'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Marp CLI
        run: npm install -g @marp-team/marp-cli

      - name: Build PPTX
        run: |
          marp slides.md --pptx --allow-local-files -o slides.pptx
        env:
          # This tells Marp exactly where the Chrome binary is located on Ubuntu runners
          CHROME_PATH: /usr/bin/google-chrome

      - name: Build PDF
        run: |
          marp slides.md --pdf --allow-local-files -o slides.pdf
        env:
          CHROME_PATH: /usr/bin/google-chrome

      - name: Commit and Push PPTX
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add slides.pptx
          git add slides.pdf
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto-generate slides"
          git push
